---
development:
  cloud_name: dkgpmjfhb
  api_key: '683146733454895'
  api_secret: hZQOpodvG0mKFrXm-KNWCRtnmBM
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dkgpmjfhb
  api_key: '683146733454895'
  api_secret: hZQOpodvG0mKFrXm-KNWCRtnmBM
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dkgpmjfhb
  api_key: '683146733454895'
  api_secret: hZQOpodvG0mKFrXm-KNWCRtnmBM
  enhance_image_tag: true
  static_image_support: false
